### ISSUE TITLE
Xcode build failed with 'library not found for -lPods-React'

### ISSUE THREAD

**Issue by jsierles** [zetachang/opal-native#1]
I ran all the setup steps and got this when building the XCode project:

Ld /Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Products/Debug-iphonesimulator/SampleApp.app/SampleApp normal x86_64
    cd /Users/joshua/code/opal-native
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -L/Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Products/Debug-iphonesimulator -F/Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Products/Debug-iphonesimulator -filelist /Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Intermediates/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/SampleApp.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lPods-React -licucore -framework JavaScriptCore -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.1 -lPods -Xlinker -dependency_info -Xlinker /Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Intermediates/SampleApp.build/Debug-iphonesimulator/SampleApp.build/Objects-normal/x86_64/SampleApp_dependency_info.dat -o /Users/joshua/Library/Developer/Xcode/DerivedData/SampleApp-egeupidrbrejlieloksxvulnkcga/Build/Products/Debug-iphonesimulator/SampleApp.app/SampleApp

ld: library not found for -lPods-React
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zetachang** [comment]
Are you build on  `SampleApp.xcworkspace`? Build on `SampleApp.xcodeproj`will lead to similar error.

**Comment by jsierles** [comment]
Oops, you're right! Working great now. Thanks for this cool project!
